### ISSUE TITLE
Extension doesn't work with ESPN redesign

### ISSUE THREAD

**Issue by jforgy** [sglantz/FantasyLink#11]
ESPN redesigned their fantasy baseball site this year and the extension no longer displays links next to player names

**Comment by msuareo** [comment]
I am running into the same issue. WiIl this extension be updated to be compatible with ESPN's new layout?

**Comment by sglantz** [comment]
I just took my first look through the new ESPN redesign and I should be able to update the extension to work with the changes.  I will dig into it more over the next few weeks and plan to hopefully have everything back up later in spring training.  

Thanks for the heads up on the redesign and the patience while I get a fix in place.

**Comment by jtbylsma** [comment]
Just want to say thanks to sglantz.  This extension is awesome and I was so disappointed to see that it no longer worked with ESPNs new UI.  Great to hear that you're working on a solution!

**Comment by sglantz** [comment]
I have things mostly working with the ESPN redesign.  The current version isn't as reliable as it was on the old design.  Hopefully I get a chance iron out the bugs soon.  But I wanted to get something up with opening day quickly approaching.
