### ISSUE TITLE
ESPN

### ISSUE THREAD

**Issue by wkolb** [sglantz/FantasyLink#12]
Still not working with espn.  Sometimes it'll show up but not often.  Any fix coming?

**Comment by sglantz** [comment]
The ESPN interface was rather buggy at the start of the season.  I was assuming there would continue to be changes to it and didn’t want to invest too much time investigating the CSS structure.  However, I eventually got tired of waiting and decided to roll out a fix that is much more aggressive in watching for page changes on ESPN.  This isn’t an efficient solution, so I may come back to change it later, but it at least solves the short-term problem of getting the links to show up consistently.
