### ISSUE TITLE
Suggestion: add link to player highlights

### ISSUE THREAD

**Issue by Drixy1123** [sglantz/FantasyLink#13]
Hi,

There is a [chrome extension](https://chrome.google.com/webstore/detail/highlights%20/ndeobkgdldlmalcpkldhdadlhneajkco?hl=en-US) that adds an icon linked to a fantasy player's highlights, but it does not work for the new ESPN site.

Do you think this would be difficult/worthwhile to incorporate with baseball.theater?:
https://baseball.theater/Search/nick%20senzel

Thanks

**Comment by sglantz** [comment]
I haven't seen that baseball.theater site before.   It seems like it would be a fun addition to the extension.  It also looks like it would be straightforward to get this implemented similarly to the other website links (i.e. not like that Highlights+ extension seems to handle it with the video popping up on the same page).  I should hopefully get some time in the next week or two to give it a try.  I will post back here with any updates.

**Comment by Drixy1123** [comment]
Awesome dude thanks!

**Comment by sglantz** [comment]
This update was just pushed out to the Chrome Web Store.  Thanks for the suggestion.
