### ISSUE TITLE
Not working for Yahoo

### ISSUE THREAD

**Issue by Hurtya** [sglantz/FantasyLink#3]
Hi - I love this, and it's a great idea.  However, it doesn't seem to be working on Yahoo?

**Comment by githubsmilo** [comment]
@Hurtya 
FantasyLink is working on Yahoo now. 
* If your roster-edit-mode is 'Swap Mode', Click right mouse button on some yahoo link and select 'open link in new tab'.
* If your roster-edit-mode is 'Classic Mode', just click it! :)

**Comment by JJMcPython** [comment]
Hello
Thank you far a great Chrome Extension.  I used this daily last year in my yahoo fantasy league.
Unfortunately, I am having trouble getting it to work this year.  I have tried the yahoo my team page in both 'Swap Mode' and 'Classic Mode' but never see any of the familiar icons next to the player names that I always saw last year.

Am I doing something wrong?

Thank you in advance.

Jacob

**Comment by JJMcPython** [comment]
It's working in my Yahoo League now!  

Awesome!  Thank you Fantasy Link!!!!!!!!!

**Comment by JJMcPython** [comment]
OK, not sure why but it stopped working again.  It was sorking great for a few hours yesterday now I can't get anything.  Uninstalled the extension, reinstalled.  Closed chrome, restarted computer.  Still no luck.

Any help would be great.

Thanks again for a very cool extension.

--Jacob

**Comment by ktarrant** [comment]
Not working for me in Yahoo. Don't see anything in Swap or Classic mode. Thanks for any help.

**Comment by ktarrant** [comment]
Hello, I fixed my problem. It just wasn't matching the https Yahoo url. Pull request here: https://github.com/sglantz/FantasyLink/pull/4

Workaround is to go to your league page, then edit the URL to be "http" instead of "https" and then all the links show up.

**Comment by JJMcPython** [comment]
Thank you ktarrant!
That fixed my problem (http instead of https).  

Really appreciate the help!
--Jacob

**Comment by Hylander1** [comment]
I thought I knew my way around software and such. But how does one go about making this https to http edit? Step by step would be helpful.

**Comment by sglantz** [comment]
Sorry for the lack of response on my end.  I have recently moved and changed jobs so I haven't had the chance to spend much time on my side projects.  I will merge in the pull request from @ktarrant and updated the extension on the Chrome web store.  @Hylander1 all you have to do at that point it wait for the updates to pull through to your browser.
