### ISSUE TITLE
Extension does nothing

### ISSUE THREAD

**Issue by enjoyingcarp650** [sglantz/FantasyLink#8]
App is just greyed out on my Chrome.  Nothing happens when I click on it, no info, not links, no anything

**Comment by sglantz** [comment]
My first troubleshooting tip and an issue other users have run into in the past is to check Chrome's permissions for the extension.  Chrome requires that certain features of an extension need to be approved before the extension can be enabled.  Try checking the extension page in Chrome's setting to make sure the enabled checkbox is clicked and any permission requests have been approved.  You can also open up the extension's options from that page to make sure that the specific features you are looking to use are enabled for the specific websites you are using.

Another possible issue is that the extension will not be enabled on any page that isn't specifically listed in the [manifest.json ](https://github.com/sglantz/FantasyLink/blob/master/manifest.json#L15).  Keep in mind that only contains a subset of pages on the fantasy sites for ESPN, CBS, and Yahoo.

Beyond that, I am sorry to say everything is working on my machine.  If those steps don't fix your issue can you provide more information regarding the specifics of the problem you are seeing?  Details like your Chrome version, whether this was a new install or a new problem on a previously working install of the extension, the URLs you are trying to access, and the current options configured for the extension could be a big help in narrowing down the specific bug.

**Comment by sglantz** [comment]
Closing this because the original user never reported back.
